org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true


# Mod Info
mod_id = registratelib
mod_name = RegistrateLib
mod_version = 2.0.0
mod_description =
mod_license = Mozilla Public License Version 2.0
mod_url = https://github.com/ModularMCLib/RegistrateLib/
mod_issue_tracker = https://github.com/ModularMCLib/RegistrateLib/issues/
maven_group = com.modularmc.registrate
